web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
    - "8080:80"
  volumes:
    - ./app:/www
    - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf  
  links:
    - php
php:
  image: php:7.3-fpm
  #build:
  #  context: ./docker/php
  container_name: php-fpm
  volumes:
  - ./app:/www
  links:
  - database
database:
  image: mysql:5.7
  container_name: mysql
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: escola_xpto